version: '3.9'

services:
  app:
    build: .
    expose:
      - 5000
    volumes:
      - static_volume:/app/static
    networks:
      - net

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    networks:
      - net

networks:
  net:

volumes:
  static_volume:
